name: Release

on:
    push:
        branches: 
            - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8 safety

      - name: Run linters
        id: run-linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          safety: true

  ReleaseBuildPush:
    name: Release
    needs: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  # if: ${{ jobs.run-linters.outcome == 'success' }}
  # packer:
  #   runs-on: ubuntu-latest
  #   name: Run Packer
  #   steps:
  #     - name: Run `packer init`
  #       id: init
  #       run: "packer init ./docker-ubuntu.pkr.hcl"

  #     - name: Run `packer validate`
  #       id: validate
  #       run: "packer validate ./docker-ubuntu.pkr.hcl"

  #     - name: Run `packer build`
  #       id: build
  #       run: "packer build ./docker-ubuntu.pkr.hcl"