name: Release

on:
    push:
        branches: 
            - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python linters
        run: pip install flake8

      - name: Run linters
        id: run-linters
        run: flake8 .

  run-safety:
    name: Run safety
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install setuptools
        run: pip3 install --upgrade pip setuptools

      - name: Install safety
        id: run-safety
        run: pip install safety && safety check

  docker-buildx:
    name: Docker Buildx
    needs: [run-linters, run-safety] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  packer:
    runs-on: ubuntu-latest
    name: Run Packer (init, validate, build)
    needs: [run-linters, run-safety] 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        id: setup
        uses: hashicorp/setup-packer@main

      - name: Run `packer init`
        id: init
        run: "packer init ./docker-ubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./docker-ubuntu.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./docker-ubuntu.pkr.hcl"